mutation CreateDemoData @transaction @auth(level: NO_ACCESS) {
  user_insertMany(
    data: [
      {
        id: "550e8400-e29b-41d4-a716-446655440000"
        displayName: "demouser1"
        createdAt: "2024-04-01T00:00:00Z"
      }
      {
        id: "550e8400-e29b-41d4-a716-446655440001"
        displayName: "demouser2"
        createdAt: "2024-04-01T00:00:00Z"
      }
    ]
  )
  album_insertMany(
    data: [
      {
        id: "650e8400-e29b-41d4-a716-446655440002"
        title: "In Rainbows"
        artist: "Radiohead"
        createdAt: "2024-04-01T00:00:00Z"
        artworkUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/archive/e/ec/20231204062232%21In_Rainbows_Official_Cover.jpg/220px-In_Rainbows_Official_Cover.jpg"
      }
      {
        id: "650e8400-e29b-41d4-a716-446655440003"
        title: "OK Computer"
        artist: "Radiohead"
        createdAt: "2024-04-01T00:00:00Z"
        artworkUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/archive/a/a2/20231204062604%21Radiohead_OK_Computer.png/220px-Radiohead_OK_Computer.png"
      }
    ]
  )
}